# Generated by Django 5.0.6 on 2024-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_add_first_to_capture_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicachievement",
            name="award_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("external", "External"),
                    ("manual", "Manual"),
                ],
                default="internal",
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
