# Generated by Django 5.0.6 on 2024-05-25 14:46

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_add_basic_award_type"),
        ("quest", "0005_add_first_to_capture_achievement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Database ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=30, unique=True, verbose_name="Display name"),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (10, "Easy"),
                            (15, "Medium"),
                            (20, "Hard"),
                            (30, "Insane"),
                            (50, "Impossible"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(related_name="groups", to="quest.location"),
                ),
            ],
            options={
                "ordering": ("display_name",),
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("location_group"),
                models.Model,
            ),
        ),
    ]
