# Generated by Django 5.0.6 on 2024-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0006_add_claim_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicachievement",
            name="description",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
