# Generated by Django 5.0.6 on 2024-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0002_fix_coords_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedlocation",
            name="is_installed",
            field=models.BooleanField(default=False),
        ),
    ]
