# Generated by Django 5.0.6 on 2024-05-19 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_add_basic_achievements"),
        ("quest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scorerecord",
            name="basic_achievement_event",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score_record",
                to="achievements.basicachievementevent",
            ),
        ),
        migrations.AlterField(
            model_name="scorerecord",
            name="capture_event",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score_record",
                to="quest.captureevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("capture_event__isnull", False),
                    ("basic_achievement_event__isnull", False),
                    _connector="OR",
                ),
                name="ensure_linked_event",
            ),
        ),
    ]
