# Generated by Django 5.0.6 on 2024-05-21 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0002_add_basic_achievements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinates",
            name="lat",
            field=models.DecimalField(
                decimal_places=13,
                max_digits=16,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="coordinates",
            name="long",
            field=models.DecimalField(
                decimal_places=13,
                max_digits=16,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Longitude",
            ),
        ),
    ]
