# Generated by Django 5.0.6 on 2024-05-25 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0005_add_first_to_capture_achievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawcaptureevent",
            name="wifi_bssid",
            field=models.CharField(
                default="00-00-00-00-00-00",
                help_text="IEEE 802 format, e.g 12-34-56-78-90-AB",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9A-F]{2}[-]){5}([0-9A-F]{2})$",
                        "The MAC address does not appear to be in the correct format.",
                    )
                ],
                verbose_name="WiFi BSSID",
            ),
        ),
        migrations.AlterField(
            model_name="rawcaptureevent",
            name="wifi_channel",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rawcaptureevent",
            name="wifi_rssi",
            field=models.IntegerField(default=0),
        ),
    ]
