# Generated by Django 5.0.6 on 2024-05-25 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0006_remove_wifi_fields_one"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawcaptureevent",
            name="wifi_bssid",
        ),
        migrations.RemoveField(
            model_name="rawcaptureevent",
            name="wifi_channel",
        ),
        migrations.RemoveField(
            model_name="rawcaptureevent",
            name="wifi_rssi",
        ),
    ]
