# Generated by Django 5.0.4 on 2024-04-27 12:39

import django.db.models.functions.text
from django.db import migrations, models

import gchqnet.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", gchqnet.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                error_messages={"unique": "Another player already has that display name"},
                max_length=30,
                unique=True,
                verbose_name="display name",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("display_name"),
                name="unique_display_name",
                violation_error_message="Another player already has that display name",
            ),
        ),
    ]
