# Generated by Django 5.0.6 on 2024-05-18 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_user_api_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="secret",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="badge",
            name="mac_address",
            field=models.CharField(
                help_text="IEEE 802 format, e.g 12-34-56-78-90-AB",
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9A-F]{2}[-]){5}([0-9A-F]{2})$",
                        "The MAC address does not appear to be in the correct format.",
                    )
                ],
                verbose_name="MAC Address",
            ),
        ),
    ]
